---
title: "G.O.A.T. Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
params: 
  week_num: 2
---

```{r setup, include=FALSE}
library(flexdashboard)

week_num <- params$week_num
source("01_scripts/call_script.R")
run_it_all(week_num = week_num)
```

Overview
===============================

Row {data-height=50}
-------------------------------------

### 

```{r}
valueBox(value = str_c(max_team, ": ", max_points), caption = str_c("Top points award for week ", week_num), icon = "fa-pencil")
```

### 

```{r}
valueBox(value = str_c(min_team, ": ", min_points), caption = str_c("Least points award for week ", week_num), icon = "fa-pencil")
```

Row {data-height=50}
-------------------------------------

### 

```{r include=FALSE}
total_mug <-str_c(unlist(t(max_points_tally %>% mutate(n = str_c(n,"<br>")))),collapse = " ")
```


```{r}
valueBox(value = "Top Points Tally",
caption = total_mug,
icon = "fa-pencil")

```

###

```{r include=TRUE}
total_min <-str_c(unlist(t(min_points_tally %>% mutate(n = str_c(n,"<br>")))),collapse = " ")
```


```{r}
valueBox(value = "Loser Tally", caption = total_min,icon = "fa-pencil")

```

Row {data-height=350}
-------------------------------------
   
### 

```{r}
luck_chart
```   
    
### 

```{r}
projected_plot
```

