name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'GOAT_Dashboard.html'
        destination_repo: 'dusty-turner/blog-reboot'
        destination_branch: 'master'
        destination_folder: 'static/GOAT'
        user_email: 'dusty.s.turner@gmail.com'
        user_name: 'dusty-turner'
        commit_message: 'auto ff committ'